import time
import os


print("Loading")
time.sleep(2)
os.system("cls")
print("--------------------------------------")
print()
print("     SPEED UP   BY AYMAN BOURAAMANE   ")
print()
print("--------------------------------------")
print()
input = input("Type Any word to start!")
print(input)
print("Clear up RAM memory")
os.system("sudo purge")
os.system("cls")
print("Clear up RAM memory (DONE)")
print("=Flush DNS Cache")
os.system("sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder;")
os.system("cls")
print("Clear up RAM memory (DONE")
print("Flush DNS Cache (DONE)")
print("Clear user log files")
os.system("cd ~/Library/Logs")
os.system("sudo rm -rf ~/Library/Logs/*")
os.system("cls")
print("Clear up RAM memory (DONE")
print("Flush DNS Cache (DONE)")
print("Clear user log files (DONE)")
print("Remove System Logs")
os.system("sudo rm -rf /private/var/log/*")
os.system("cls")
print("Clear up RAM memory (DONE")
print("Flush DNS Cache (DONE)")
print("Clear user log files (DONE)")
print("Remove System Logs (DONE)")
print("Update MAC OS")
os.system("softwareupdate -l")
os.system("cls")
print("Clear up RAM memory (DONE")
print("Flush DNS Cache (DONE)")
print("Clear user log files (DONE)")
print("Remove System Logs (DONE)")
print("Update MAC OS (DONE)")
time.sleep(2)

os.system(cls)
print("Terminal will close in 3")
os.system("cls")
time.sleep(0.5)
print("Terminal will close in 2")
os.system("cls")
time.sleep(0.5)
print("Terminal will close in 1")
os.system("cls")
time.sleep(0.5)
exit()


